apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdhpai-rhdh-dev
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    repoURL: https://github.com/thepetk/rhdhpai-gitops-poc.git
    targetRevision: main
    path: ./overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: developer-hub
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
